### PR TITLE
Fix vehicle stop at yield sign if no traffic

### PR DESCRIPTION
**Pull request by krzychu124**
Fixes issue with vehicle stopping at yield sign if no incoming traffic on main road

### CODE REVIEW

**Comment by aubergine10** [comment]
How much of a pause are they expected to make when entering via Yield sign? For me they still seem to be slowing down a lot... (will post vid to discord in a bit)

**Comment by aubergine10** [comment]
With Yield traffic moving so smoothly on to junction, there's no visual difference between Yield roads and Priority roads most of the time. Maybe we should also reduce the `MaxYieldVelocity` a bit? Not sure  how we'd make it update for end-users though, as their global config xml will already have the `2.5` value in it.

**Comment by krzychu124** [comment]
> Not sure how we'd make it update for end-users though, as their global config xml will already have the 2.5 value in it.

If we bump config version it will reload values, I think. 
On the other hand it looks like still something is missing, maybe value is not correct when it's passed to final speed calculation (missing conversion or something).

**Comment by aubergine10** [comment]
does this need a 'do not merge yet' label?

**Comment by krzychu124** [comment]
It looks like it works. No changes are necessary. We can make some tweaks later after feedback from users.

**Comment by krzychu124** [comment]
Hmm, compared to 10.21.1 priorities behaviour looks very very similar. I would merge it

**Comment by aubergine10** [comment]
Were we going to reduce the `MaxYieldVelocity` a bit and bump global config version to make sure it gets updated? I'll test again shortly but last time I tested this PR yield vehicles were too smooth and visually indistinguishable from priority traffic. Yield traffic should maybe slow just a little more?

**Comment by krzychu124** [comment]
@kianzarrin what are you doing????

**Comment by aubergine10** [comment]
Restored branch and reopened PR

**Comment by aubergine10** [comment]
Going to merge this as it's working and should be part of 11.1 release. I'll create an issue to change the yield velocity, that can go in to 11.2

**Comment by kianzarrin** [comment]
@krzychu124 I'm so sorry I got totally confused!

**Pull request merged**
