### PR TITLE
Update incompatible_mods.txt

### PR DESCRIPTION
**Pull request by aubergine10**
Found some additional incompat mods, and also added to the list a load of other game breaking mods (nothing to do with TM:PE but might as well flag them if users have them subbed).

### CODE REVIEW

**Comment by aubergine10** [comment]
Would it be possible to get a block comment feature in the .txt file? So any line starting with # would be ignored?

**Comment by krzychu124** [comment]
Depends on our implementation :wink: 
If you want to add more outdated or incompatible mods (not related with TM:PE)we can create different file and maybe we could display different message

**Comment by aubergine10** [comment]
Could the incompatible mod checking code be pulled in to it's own repository? I imagine it would be useful for other mods too (eg. RealTime mod could warn about Rush Hour II)

**Comment by krzychu124** [comment]
Ok, no problem, go ahead :wink: :+1:

**Comment by pcfantasy** [comment]
@aubergine10 

Nice, I also want to use this powerful codes.

**Comment by krzychu124** [comment]
It could be improved by adding a scan for offline(noWorkshop) mods located in users appdata

**Comment by aubergine10** [comment]
@krzychu124 Yup. My plan currently is that there would be a ```Dictionary<string, ulong>``` to map folder names to workshop ids. This way I can use the normal workshop definitions of incompatible mods and apply them to locally installed mods.

Or were you thinking of warning users that they have both local and workshop version of mod installed?

@pcfantasy If you just want to check for incompatible mods when your own mods are activated, just rob the code from TMPE - see PR https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/pull/106

**Comment by krzychu124** [comment]
I wouldn't relay on folder names :/ you can name it like you wish and it has nothing to do with loaded dll's. Look into Plugin manager to get loaded mods (that was my idea to resolve that problem with offline content) next you can look into Content Manager class (I don't remember exact name) and search for unloading and deleting folder of selected plugin (there must something like that)

**Comment by aubergine10** [comment]
I've created a repo here: https://github.com/aubergine10/incompatible

The plan is:

* A master list defines all known broken mods by their workshop id
* Separate 'replacement' lists suggest which working mods to use
    * For a given 'upgrade' mod (working mod) it will list which  mods it replaces
    * User will click to 'upgrade' - subbing the new mod and ditching the old ones
* There will be a dependency checker (not even started on that yet)
* At the end of the process, any remaining broken or obsolete mods can be unsubbed

If you look in the repo linked above you'll sort of get an idea how it will work.

I also plan on having some stuff to deal with game patches, such as disabling mods broken by the patch (and possibly enabling them again afterwards).

Regarding local mods, I'll probably leave that for now - my current focus is allowing casual users to kick their workshop-subscribed mod list in to shape.

**Comment by aubergine10** [comment]
I'll be updating this PR with revised version of the incompatible_mods.txt - removing stuff not relevant to TMPE but maybe adding a few more mods that I've found whilst digging through the workshop.

One mod of concern is the Advanced Road Anarchy mod... I've seen quite a few reports that it's creating orphan nodes (not connected to any segments) and other weird stuff, like not properly connecting segments to nodes while placing new roads. I imagine that is going to screw quite badly with TMPE, pathfinding, etc. Should we consider it an incompatible mod? (alternatives like Fine Road Anarchy and Fine Road Tool are much more reliable compared to ARA).

**Comment by aubergine10** [comment]
Trying to define a list of dependencies, but it's moaning about the square brackets around dependency mod ids....

```
using System.Collections.Generic;

namespace Incompatible.Dependencies
{
    public static class Dependencies
    {
        public static Dictionary<ulong, ulong[]> list = new Dictionary<ulong, ulong[]>()
        {
            {689937287, [502750307] }, // Surface Painter: Extra Landscaping Tools
            {787611845, [593588108] }, // Prop Snapping: Prop & Tree Anarchy
        };
    }
}
```

**Comment by krzychu124** [comment]
Look at your definition ```Dictionary<ulong, ulong[]> -> tranlated to Dictionary<TypeOfKey, TypeOfValue>``` you should clearly see that ulong (first) will be key and second ulong[](is an array) so even if you have one entry as value assigned to the key, you have to put it in brackets

**Comment by aubergine10** [comment]
Seems I have to use the ```new``` constructor, like this:

```
namespace Incompatible.Dependencies
{
    public static class Dependencies
    {
        public static Dictionary<ulong, ulong[]> list = new Dictionary<ulong, ulong[]>()
        {
            {689937287,  new ulong[]{502750307}            }, // Surface Painter: Extra Landscaping Tools
            {787611845,  new ulong[]{593588108, 791221322} }, // Prop Snapping: Prop & Tree Anarchy, Prop Precision
            {1619685021, new ulong[]{791221322, 787611845} },  // Find It: Prop Precision, Prop Snapping
        };
    }
}
```

Is there less verbose way to do it?

**Comment by krzychu124** [comment]
This is how we initialize array so there is no other option, I think

**Comment by aubergine10** [comment]
Yeah, coming from JS I'm used to really sparse object, array and class definitions. Strictly typed monomorphic C# is a culture shock heh.

@pcfantasy I've started adding dependencies section to the mod described earlier, you can send a PR with your updates to this file: https://github.com/aubergine10/incompatible/blob/master/Incompatible/Incompatible/Dependencies/Dependencies.cs

Note: Traffic Manager stuff is already dealt with here (and in main TMPE mod itself, of course):  https://github.com/aubergine10/incompatible/blob/master/Incompatible/Incompatible/Replacements/TrafficManager.cs

**Comment by aubergine10** [comment]
I've now removed items that aren't relevant to TMPE, and also added the Realistic Vehicle Speeds mod (#213) as it clashes with TMPE feature of same name.

Should be good to merge.

**Comment by aubergine10** [comment]
Note: I have no idea how to change from master -> Labs branch in an existing PR.

**Comment by krzychu124** [comment]
Use edit 😉

**Comment by aubergine10** [comment]
I thought you or Victor had set up a Labs branch? Or is there just master and stable?

If master = Labs, then this PR should go to master as Stable doesn't yet use the incompatible mod checker code (as per comment by Victor in #213).

**Comment by VictorPhilipp** [comment]
What's the status of this PR? Can it be merged?

**Pull request merged**
