### PR TITLE
Rotate Lane Arrows GUI to Match Road

### PR DESCRIPTION
**Pull request by kvakvs**
✅ Calculates on-screen position for the edited road segment
✅ Rotates the GUI accordingly
✅ Checks if mouse within the rotated GUI window
✅ Performs special handling for curved segments.

image
image

### CODE REVIEW

**Comment by FireController1847** [comment]
I think this should be up for discussion. I can see a lot of users reporting this as a bug, and I'm not sure we're going to want this in the long run.

**Comment by FireController1847** [comment]
Closing until there's enough research to back-up people wanting/needing this feature. Preferably, can re-open for discussion after Harmony if there is still interest.

**Comment by aubergine10** [comment]
@kvakvs The lane arrow things do need to align with the road, but I agree with @FireController1847 that the implementation above is just crazy :)

We need to completely rethink the lane arrows tool at some point, but now is not the time.

**Comment by VictorPhilipp** [comment]
I love it :-D

What about introducing an option that instead makes the **camera** rotate when the user selects a segment end while the lane arrow is active? When the segment end is unselected the camera would then rotate back to its original position/angle.

**Comment by kvakvs** [comment]
@VictorPhilipp Rotating the user view could create negative impression for the user.
i am experimenting with new Canvas-based GUI which will be rendered in the ground plane. When it works I will try the same approach again with lane buttons in the ground plane.

**Pull request closed without merging**
