### PR TITLE
[Facelift] Toggle Traffic Lights show junction status

### PR DESCRIPTION
**Pull request by kvakvs**
* The tool now displays all eligible crossings with greyed out traffic light icon
* The tool now displays nodes with TL on with a white traffic light icon.
* Hover blue circle shows current hovered node (old behaviour)
* Additional filter added, only roads are allowed for traffic lights, should ignore rail, metro etc.
* [Bonus] optimized distance calculations in all tools where they used `magnitude` for each node/segment instead of `sqrMagnitude`

# Checklist

- [ ] Replace TL texture with classic on/off traffic light
- [ ] Visualize timed traffic lights where they are set

image

Contributes to #523

### CODE REVIEW

**Comment by aubergine10** [comment]
Love the concept, much clearer to see what the state of each junction is.

However, could we use a simpler design for the lights icon? Something like the vanilla game uses - where disabled is round cornered grey rectangle, and enabled is black with coloured lights?

**Comment by kvakvs** [comment]
We absolutely can. I need to find how to get the Texture2D from the game, and to know its size (aspect ratio). Or create exact same looking texture.

**Comment by aubergine10** [comment]
I think Mod Tools might have some way to extract textures and dump them to disk.

Ronyx made this video about dumping textures - not sure if it covers the vanilla junction icons tho: https://www.youtube.com/watch?v=nzJK77BU2Lg

There are also some tools listed here: https://cslmodding.info/dump/#unity-assets-bundle-extractor

I think @krzychu124 also found some way to dump all textures in the game.

**Comment by kvakvs** [comment]
I have installed dump textures mod once, the output might still be somewhere on my drives.

**Comment by kvakvs** [comment]
@aubergine10 In any case the traffic light icon is the same icon used in the new concept for the main menu buttons. Which is why it looks closer to new proposed TM:PE style, and further away from the game style.

**Comment by aubergine10** [comment]
Would it be worth trying the simplified design for the new menu buttons also?

**Comment by kvakvs** [comment]
Yes if you can replace round button with square, and slap on the new textures it might give an impression of how it will work together.
I can show some mighty paint skills and smash them together.
image

**Comment by aubergine10** [comment]
Speaking of flat button, I tried altering the normal button as you suggested, but was thwarted by this method:

image

All I need to do is change `color` value between those calls. But.. I don't seem to be able to override that in a custom class. So I tried digging deeper, but things just get worse, with `internal` and `protected` methods/properties in the `UIInteractiveComponent` class which in turn relies upon an `internal struct` of the `UISprite` class.

Maybe it's just my lack of C# knowledge, but it seems that the person who created the C:SL UI framework has specifically designed it in such a way to obstruct people from creating custom or tangibly modified interactive elements.

My current half-baked solution is to extend `UIPanel` and create two `UISprite` inside it during instantiation, but even then the way panels work is so utterly obtuse that it would be difficult to overlay the two sprites or introduce some internal padding between the background and foreground sprites. Hence me attempting to use `UIButton` instead. This UI framework gives me PTSD.

**Comment by kvakvs** [comment]
Let's agree on the style then.
1. We liked how the main menu looks and this will be the new style. If the answer is yes, I have a prototype of a canvas UI which will grow into a separate PR updating the main menu.
2. Do we use the new style icons on overlays too, or prefer the old style game icons? If the answer on 2 is yes, we will need to find another icon collection to pick the icons from.

**Comment by kvakvs** [comment]
* Changed TL textures to use standard TL on/off texture from the game
* Added a timer texture for nodes with timed TL

image

**Comment by krzychu124** [comment]
Looks nice, maybe icon is a bit too small. I know, I know it's still bigger than vanilla toggle 😃

**Pull request merged**
