### PR TITLE
Minor fixes: Saving/Loading junction restrictions, UI overlay, Reset stuck cims

### LINKED ISSUE #351: Reset stuck cims (maintenance tab) unpauses game
Only a minor glitch:

When you go in to TM:PE options from the Pause menu, and click "Reset stuck cims and vehicles" button on the Maintenance tab, the game unpauses while the options screen is still visible.

It doesn't seem to cause any issues, but just odd that the game unpauses while still in mod options.

### PR DESCRIPTION
**Pull request by VictorPhilipp**
- Fixed minor issues regarding saving/loading junction restrictions
- Bugfix: Changes of default junction restrictions are not reflected in the UI overlay
- Bugfix: Resetting stuck cims unpauses the simulation (#351)

Fixes #351

### CODE REVIEW

**Comment by aubergine10** [comment]
Need to do some more testing on this - had some weird glitches but a few other mods were just updated so possibly caused by them. Please don't merge until I can confirm the glitches were external factors.

**Comment by aubergine10** [comment]
Good news, it's not TM:PE, so this can be merged.

Narrowing down recently updated mods:

* ~~Watch It~~ - bit broken by latest update, but not causing the issues
* Real Time
* Snooper
* Resize It
* Hide It

**Comment by aubergine10** [comment]
Tested every combination of the recent updates with and without TMPE. Bulk of issues form recent update to "Watch It" mod, and some from "Show It" mod.

TM:PE is 👍

**Comment by VictorPhilipp** [comment]
Thanks for the extensive testing!!

**Pull request merged**
