### PR TITLE
boost lane marker hovering

### LINKED ISSUE #625: lane connector should raycast the whole lane
see #543 

in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/543#issuecomment-549069179 @krzychu124 fixing the rendering problem.

EDIT: the current ray-casting would work just fine. 
meanwhile this issue is for making it easier to hover over lane node markers by making the whole lane hover-able.

~~This issue is for fixing the ray-casting problem.
I intend to use `GetClosestLane()`. should be a piece of cake! ~~

### PR DESCRIPTION
**Pull request by kianzarrin**
fixes #625
added `DetermineHoveredLane()` to `DetermineHoveredElements()`. Then I use this to find the correct lane marker.

declared `HoveredLaneID` in `TrafficMangerTool` and `SubTool`.

Additionally I took the opportunity and removed setters from `SubTool.HoveredNodeID` and `SubTool.HoveredSegmentID`. Such setters are unused, unnecessary and using them can cause bugs.

### CODE REVIEW

**Comment by kianzarrin** [comment]
@krzychu124  
> It doesn't fix anything regards raycasting. 

There was a rendering issue and there was a raycasting issue. I changed the raycasting to use all the lane area rather than only  marker. I have a feeling that when you say fix raycasting you mean something else.

> not to mention it makes detection a bit slower (~40-50%)

Yeah I was worried about the performance. other pull requests I created reduce performance even more. There are ways to increase performance but should I? I mean 0.1ms is not much is it? If it is then we should create an issue and I can work on some ideas I have.

**Comment by kianzarrin** [comment]
This is really bad with bridges. I need to fix this.

**Comment by kvakvs** [comment]
Lane marker raycast should not target the ground level but the road plane, at the height where the marker is located. Then it will always look correct, at any height on or under any bridge.

**Comment by kianzarrin** [comment]
@kvakvs 
> Lane marker raycast should not target the ground level but the road plane,
My biggest problem with lane markers is when a truck is over it. targeting road plane does not help with that.
I am using mouse pos instead of hit pos which is wrong. I will fix that right now.

**Comment by kianzarrin** [comment]
@krzychu124 
> it makes marker selection weird in some cases

what is the expected behavior? 
- in https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/543#issuecomment-549066621 we agreed that I need to make the whole lane hoverable
- should I highlight the lane or only the lane marker? ( i prefer lane marker because I don't want it to look like xmass)
- what should be the behavior when the mouse pointer is on the node, should I highlight closest marker or should I hover nothing? (I prefer highlight closest lane marker)

**Comment by kianzarrin** [comment]
This still doesn't work when there is a bridge passing by.

**Comment by aubergine10** [comment]
testing...

**Comment by aubergine10** [comment]
Overall I like where this is heading; when it works, it works really well - much easier to pick and place the connector lines.

However, there are still some issues. You're probably aware of these, but I'll go through each one I found just in case...

1. Roads under bridges are cumbersome to work with

* Difficult to select node
* Difficult to select lane markers

under brdige

2. Tunnels are also cumbersome to work with

* Difficult to select lane markers
* Underground view (`PgDn` while tool active; see last section of GIF) doesn't improve usability

tunnel

3. Road bridges can be cubersome to work with

* Difficult to select lane markers on the bridge

road bridge

4. Rail bridges are more cumbersome to work with

* Difficult to select lane markers
* The connector line does not appear

rail bridge

5. Nodeless junctions make some markers inaccessible

* A nodeless junction can result in lane markers appearing on top of each other
* Only the topmost marker can be selected
* Example below is from [Railway](https://steamcommunity.com/sharedfiles/filedetails/?id=1569088356) collection; most of its networks have nodeless variants
* Any network that offers nodeless junctions (eg. some [CSUE roads](https://steamcommunity.com/workshop/filedetails/?id=1206133771))
* I think in recent [CSUR Toolbox mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1959342332) they found a workaround (see "Bug Fixes" section in description of that mod)

nodeless

6. Things I didn't test:

* Monorails
* Tram roads (in particular the [LRT networks](https://steamcommunity.com/workshop/filedetails/?id=1560202570) - especially [sinking one](https://steamcommunity.com/sharedfiles/filedetails/?id=1725915787) - by clus will need testing)
* Metro
* The CSUE, CSUR, etc roads by AmamIya

**Comment by kianzarrin** [comment]
@aubergine10 OH no! why did you tested something I already had said it won't work? I was waiting for you guys to tell me if I should close down this review:
Screenshot (374)

I am doing it now!

**Comment by aubergine10** [comment]
I liked the premise of the idea; in the places where it worked, it worked really well and made it easier to interact with the lane markers; sadly it just made other places much more difficult.

**Pull request closed without merging**
