### PR TITLE
Parking AI loop

### LINKED ISSUE #259: Parking AI: Infinite loop when parking spaces cannot be found
as reported by @leaderofthemonkeys via Discord.
https://gyazo.com/7f7311ba45fba9632e8ff4aa7928a1fc

> # Temporary workaround:
> 1. Check you don't have duplicate copy of "Advanced Vehicle Options" mod installed - only use one version, unsubscribe the other.
> 2. To remove stuck vehicles: Click vehicle to show info panel, then click despawn to despawn the vehicle.

### PR DESCRIPTION
**Pull request by VictorPhilipp**
- Parking AI: Last segment before parking space is now required to be accessible by car
- Bugfix: Random parking broken
- Bugfix: Pedestrian crossing restriction affects road-side parking
- Pedestrian crossing is allowed at untouchable bent nodes
- Removed u-turn lane arrow check at transition nodes

Fixes #259

### CODE REVIEW

**Comment by aubergine10** [comment]
I'm not sure if this is related to this PR, but if I enable "Vehicles may u-turn at junctions" in mod options, it enables u-turns at transition nodes like this:

transition

**Comment by aubergine10** [comment]
Also bend nodes:

bend

**Comment by aubergine10** [comment]
Although not at this bend?

not

**Comment by VictorPhilipp** [comment]
I have not changed anything regardin the u-turn junction restriction in this PR. Would you like to create a seperate bug report for this?

**Comment by aubergine10** [comment]
Yup, will do.

**Comment by VictorPhilipp** [comment]
Might also be a UI overlay issue which was addressed by PR #358

**Comment by aubergine10** [comment]
> Parking AI: Last segment before parking space is now required to be accessible by car

Not sure how to test this.

> Bugfix: Random parking broken

Again, not sure how to test, but parking seems to be working fine (cleared all traffic and vehicles are parking where I expect them to park).

> Bugfix: Pedestrian crossing restriction affects road-side parking

Not sure if this is working. I have parking roads along a quay on a lake in my city and vehicles were parking there fine before.

I disabled pedestrian crossings as shown on image below, then cleared all traffic and parked cars, then let the game run for about 20 mins:

ped parking

They are parking near the white housing blocks on the left of the image, where ped crossings are enabled, but they aren't parking on the segments along the wooden pier, where ped crossings are disabled.

> Pedestrian crossing is allowed at untouchable bent nodes

Not sure how to test this.

BTW, some possibly related stuff (pedestrian crossings) from the old github repo:

* https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/101
* https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/168

**Comment by aubergine10** [comment]
Forgot to mention: The road assets I'm using ([UK Roads Revived](https://steamcommunity.com/sharedfiles/filedetails/?id=1601040013) by Macwelshman) don't have pedestrian crossing decals.

download

**Comment by aubergine10** [comment]
After waiting almost an hour with game running, there was still no parking on the roads near the wood pier.

I then enabled some ped crossings near block of white houses, and after a while got a few vehicles parking there as shown below (one of the parked cars is under the UI overlay):

some park

On the side where ped crossing remains disabled, still no parking (there is a bus stop on that segment but other side of road should still allow parking), and still no parking further to the right as per previous image.

Will continue testing but from what I can see disabling a ped crossing kills parking on one or both adjacent segments.

**Comment by VictorPhilipp** [comment]
I have tested that with a 6-lane road where I forbid crossings at both ends:
grafik
Cars are able to park. I will set more restrictions.

**Comment by VictorPhilipp** [comment]
grafik

Works for me

**Comment by VictorPhilipp** [comment]
Is parking allowed? And do you have a savegame for me? :-)

**Comment by VictorPhilipp** [comment]
I guess it's not impossible for them to park there but unfavourable

**Comment by aubergine10** [comment]
I'll do some more testing on this later today. The city I'm testing on currently is very small so possible that there just aren't enough cars to properly test. I'll splat down some additional RICO to bump population and traffic.

**Comment by aubergine10** [comment]
I provided a binary of this PR for testing against the issues raised in #342, here is the feedback from @s2500111:

> As far as I can tell, they seem to distribute better over the available parking spots and stopped piling up in the first neighborhood.
>  
> But the issue with cars stopping right before the bus stop isn't solved.

**Comment by aubergine10** [comment]
As per #342, it seems the problem I was having is due to a bus stop on that road. I've briefly tested by removing the bus stop and cars are already starting to park there.

**Comment by aubergine10** [comment]
@krzychu124 This PR looks good to go, do you have any comments from code perspective?

**Comment by krzychu124** [comment]
LGTM :+1:

**Pull request merged**
