### PR TITLE
Esc key handler

### LINKED ISSUE #92: ...at TrafficManager.UI.UIBase.Finalize ()
Getting this at end of my log file, apparently something to do with recently updated ```Esc``` handler.

```
Colossal Handler caught: 
  at (wrapper managed-to-native) UnityEngine.Component:GetComponentFastPath (System.Type,intptr)
  at UnityEngine.Component.GetComponent[CustomKeyHandler] () [0x00000] in <filename unknown>:0 
  at TrafficManager.UI.UIBase.Finalize () [0x00000] in <filename unknown>:0
```

### PR DESCRIPTION
**Pull request by krzychu124**
Fixes #92 

Additionally I've deleted part of post-build script with old stuff which copy compiled libraries to workshop item folder location. 
I don't need that.

### CODE REVIEW

**Comment by aubergine10** [comment]
You'll have to explain to me how I build the mod locally before I can test :)

Could you create a page in main repo outlining how to build and test locally?

**Comment by krzychu124** [comment]
Yup, wait a minute or few hours 😄
I've tested that :wink: 

BTW this message is harmless since it occurs when user closing the game (onLevelUnload() - almost end of log file). Correct me if I am wrong.

**Comment by aubergine10** [comment]
Yeah, it's a silent error that doesn't seem to cause any issue that I'm aware of.

**Comment by krzychu124** [comment]
Even better, this part of code is trying to destroy key handler attached to Main Menu to prevent memory leaks but it seems that menu was destroyed earlier.
Additionally it happens only when closing the game so it does not matter if I destroy it or not, all memory used by game is wiped out anyway.

**Pull request merged**
