### PR TITLE
fixed hovering error by using distance instead of angle

### LINKED ISSUE #576: Better segment hovering raycast
in #564 I made it easier to hover over small segment. Even so hovering can still be hard for small junctions. I think this is a caveat with skylines built-in ray-cast but I think I have a work around.

Here is the problem:
Cities_Ct6sactalI
In the picture above I have demonstrated a situation in which its very hard to select the highlighted segment end. In fact the 2 mouse positions in the picture above are the only places the mouse can be to select the desired segment end. You notice that the mouse is near the right segment but still the left segment is selected. This is not right. I think that the selection areas should be like this:
Screenshot (124)
Terminology:
- hover area: the area the mouse pointer should be in in order to chose the desired segment end. In picture above its red stakes.
- highlight shape: the shape of the highlight which is a blue half sausage.

Note that I want to change the hover area only. The highlight shape is and shall remain half sausage.

### PR DESCRIPTION
**Pull request by kianzarrin**
Fixes #576 
as discussed here https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/576#issuecomment-578488331 I used `GetClosestPost()` to hover over the right segment.

I tested my code, the hovering boost still applies when the mouse pointer is on the node.

I also tested for segment with extreme curves:
Screenshot (350)

### CODE REVIEW

**Comment by kianzarrin** [comment]
I accidentally pushed in my changes for another issue and then I reverted it back. so everything should be fine now.

**Comment by kianzarrin** [comment]
I totally forgot to test this on a bridge. This is a low moment for me!

**Comment by aubergine10** [comment]
I think we should get https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/576#issuecomment-578488331 resolved prior to releasing v11; hover selection issues would be highly annoying for users. I've added this to 11.0 milestone.

**Comment by kianzarrin** [comment]
Damn it! I totally forgot to test this on a bridge. 
I should not use mouse pos but rather should use hitpos
here i fixed it:
ezgif com-optimize

**Comment by aubergine10** [comment]
From end-user perspective, seems to work well. 

Some queries:

1. Are bridges (eg. where ground transitions to elevated or bridge) supposed to have lane arrows?
2. Is first 'full tunnel' segment after a tunnel entrance (ie. not joined to the tunnel entrance node) supposed to have lane arrows?
3. Are one way roads supposed to support lane arrows (eg. where they transition from ground to bridge, etc)?

Things tested:

* 👍 Insanely short and/or narrow roads
* 👍 Extremely curved roads
* 👍 Tunnel entrances
* 👍 One way roads
* 👍 Road and rail at ground level
* 👍 Road and rail elevated level
* 👍 Road and rail bridge level
* 👍 Non-transit netwoks (pipes, fences, etc) didn't get selected
* 👍 Didn't seem to have any adverse effect on framerate for me

Not tested:

* Code quality
* One-way rail or single rails
* Metro, tram, monorail

**Comment by kianzarrin** [comment]
@aubergine10 
> * Are bridges (eg. where ground transitions to elevated or bridge) supposed to have lane arrows?
>   
>   * I can see the use if the number of lanes changes; but it was also highlighting elevation transitions where number of lanes were identical on both sides.
> 
> * Is first 'full tunnel' segment after a tunnel entrance (ie. not joined to the tunnel entrance node) supposed to have lane arrows?
>   
>   * Like bridges above, is it valid that a tunnel entrance can have lane arrows if the ground and tunnel segments have identical number of lanes on both sides?
> 
> * Are one way roads supposed to support lane arrows (eg. where they transition from ground to bridge, etc)?

The lane arrows are outside the scope of this review. I am testing this with the lane arrow tool only to test if my code works because its the only one that I can think of that hovers over segment ends.

As for the answer to your questions The vanilla game does put lane arrows for them! because it is setting up the junction flag. It does not make sense for me either. that said in TMPE we can take advantage of this and provide opportunity for U-turn.

Screenshot (377)

**Pull request merged**
