### PR TITLE
Turkish and Ukrainian language support

### PR DESCRIPTION
**Pull request by krzychu124**
Added Turkish and Ukrainian language support.
- `tr` : `ISO 639-1` Turkish language id (Tayfun[Typhoon] (Koop on Steam)),
- `uk` : `ISO 639-1` Ukrainian language id (kvakvs),
- updated translations,
- included new Auto Traffic Lights (#554 ) translation keys

### CODE REVIEW

**Comment by krzychu124** [comment]
Tayfun[Typhoon] (Koop on Steam, I think) I will add one more commit later today, because I see that he added more translations

**Comment by kvakvs** [comment]
**krzychu124: Assigning multirow text to single string wasn't the best idea. @kvakvs🚦 you've added invisible line break in Tooltip.Keybinds:Change lane arrows which breaks generated translation row to two lines, Alt+Клік tooltip text is not visible in game :/**
bild

**Comment by aubergine10** [comment]
On a cursory glance, line break issue is fixed. LGTM 👍

**Comment by krzychu124** [comment]
Yes, I fixed it, but I will refactor it later( #574 )

**Pull request merged**
