### PR TITLE
Enforce stating explicit types

### PR DESCRIPTION
**Pull request by VictorPhilipp**

### CODE REVIEW

**Comment by kvakvs** [comment]
This is going to break the builds in so many exciting ways.
On very long generic types this will look even longer.
Also this will require using `#if` where types can be different and a `var` was enough before.

**Comment by VictorPhilipp** [comment]
It will (sadly ^^) not breaking the build because Rosyln analyzer does not support .NET 3.5. However, it will be marked as an error in the IDE (but compiling works fine).

Why should we only use strictly typed variables? Having to state every variable type is tedious and makes the code verbose, yes. But it also helps with readability (no need to hover of the variable to see the type). Since we do not have unit tests (yet) the code base is quite fragile: For example, when a method return type is changed only if the calling code uses explicitly typed variables our build fails and we get a chance to see and fix it immediately.

**Comment by kvakvs** [comment]
In #430 I am now going through every file, and changing vars to types is essentially a one-click operation to apply that to a file, directory or whole project. As I am visiting every file anyway, I can do that. This will save you the work on this branch.

**Comment by dymanoid** [comment]
@VictorPhilipp, Roslyn Analyzers don't depend on the project's target framework. So you can perfectly use Roslyn analyzers with projects targeting .NET Framework 3.5 and below and issue build errors there. Or maybe I'm not getting your point?

Now to the `var` topic. It's your repo of course and you write the rules, but I would strongly discourage forbidding `var` as you propose now. First of all, generics and LINQ will become pain in the ass. Then, you won't be able to use anonymous types. Your code will become much more verbose and in fact harder to read.

What is more readable?

```
var collapsedVehicles = transportManager.GetVehicles(VehicleState.Collapsed);
return collapsedVehicles.Any();
```
or
```
ReadOnlyDictionary<VehicleId, Tuple<VehicleState, VehiclePosition>> collapsedVehicles = transportManager.GetVehicles(VehicleState.Collapsed);
return collapsedVehicles.Any();
```

Forbidding `var` introduces other risks. The code might compile but will throw runtime exceptions.

Consider this:
```
foreach (Vehicle in transportManager.GetVehicles()) { }
```
Create an interface `IVehicle` and change the return type of that method to `IVehicle`, let `Vehicle` implement `IVehicle`, add a new class `HorseCart : IVehicle` and let the `GetVehicles` return `Vehicle`s and `HorseCart`s. The code will perfectly compile, but you'll get `InvalidCastException`s in runtime.

Furthermore, if you would like to refactor and change a method return type from `Vehicle` to `IVehicle`, you would need to touch each and every file where that method is used to change the variable types. Instead of only touching one file when the usages are all `var`.

And the last point. If you think that having concrete types will help understand the code better and having `var` makes your code completely "black magic" without knowing the type, then it's the code that causes this, not `var`. The identifiers in the code must be self-explaining and generally you don't need to know at each and every line the concrete types involved (with some exceptions for high-perf and other edge cases).

Again, it's your repo but the C# community will blame you if you ban `var` just like that.

**Comment by VictorPhilipp** [comment]
> If you think that having concrete types will help understand the code better and having `var` makes your code completely "black magic" without knowing the type, then it's the code that causes this, not `var`.

You are right, but since the code **is** messy and fragile I suggested not to use `var` when possible.

> Create an interface `IVehicle` and change the return type of that method to `IVehicle`, let `Vehicle` implement `IVehicle`, add a new class `HorseCart : IVehicle` and let the `GetVehicles` return `Vehicle`s and `HorseCart`s. The code will perfectly compile, but you'll get `InvalidCastException`s in runtime.

I expected that this would cause the build to break (it at least would break in Java) but you are right.

> Then, you won't be able to use anonymous types.

Isn't that acually a good thing (in context of C:S modding and memory locality)? ;-)

> What is more readable?
[...]

I guess that highly depends on whom you ask. I would indeed answer that the second block is more readable because I don't need to do an extra check on the return type of `GetVehicles()`.

> Again, it's your repo
No, it's krzychu's repo :-)

Ok, honestly, thanks for the discussion. I did not think that this topic might cause so much controversy. Since there are more important things to address we should not invest too much time on this. I am closing the PR for now.

**Pull request closed without merging**
