### PR TITLE
Add Function to Disable & Remove Traffic Lights

### LINKED ISSUE #320: Button to remove / disable all traffic lights
Is it possible to implement a button that removes all traffic lights in your entire city? 

I tried implementing it myself but I can't figure out how to iterate the "ref NetNode node" from 0 to max and have it in a nested loop with 
`for (ushort nodeId = 0; nodeId < NetManager.MAX_NODE_COUNT; ++nodeId)`

### PR DESCRIPTION
**Pull request by Craxy**
Button to remove / disable all traffic lights

Adds a new junctions settings group under "Gameplay" to:
* disable traffic lights at new junctions
  * touches only new junctions, not existing ones
  * still allows adding lights manually -- it only prevents lights at new junctions
* remove all traffic lights at existing junctions
  * doesn't remove timed traffic lights
  * because quite drastic and undoable: confirmation dialog before execution

Fixes #320

### CODE REVIEW

**Comment by aubergine10** [comment]
Hi - sorry for delay in responding, we're currently gearing up for 10.21 release so things are a bit hectic - please bear with us, and thanks for the contribution!

**Comment by Craxy** [comment]
First I had the "Remove All Traffic Lights" button in Maintenance too (because @Sqoops put it there in #320). But the other options in Maintenance are just cleanup and don't alter the map forever, while "Remove All Lights" is quite radical and directly changes how traffic flows. That's why I added an additional confirmation dialog and moved it into the "Gameplay" Tab.

But of course I can move it back. (And in terms of layout the button would fit better into the list of other buttons than between tiny toggles ;) )

**Comment by aubergine10** [comment]
For now stick it on maintenance tab. I think at some point we'll have to rethink the mod options screen as it's getting very crowded.

**Comment by krzychu124** [comment]
Totally forgot about that PR. 🤦‍♂ 
I will create new PR and I'll move your work you've done here, because resolving conflicts in this branch is waste of time, since it's pre-Harmony version and translation system has changed after moving to CrowdIn platform.

**Pull request closed without merging**
