### PR TITLE
No lane changes at toll boothes

### LINKED ISSUE #225: Lane changes happen at toll boothes
> # Temporary Workaround
> Use the lane connector tool, click the toll booth road node(s) and then press Shift+S to set them all "ahead only"

----

They should not.

### PR DESCRIPTION
**Pull request by VictorPhilipp**
- Regular and emergency vehicles do not change lanes at toll booths anymore.
- The old erroneous solution (checking for lanes with "Merge" flag) was removed.
- The new solution checks whether the transit node belongs to a toll booth. If that's the case lane transitions that involve lane changes are not generated anymore.

Fixes #225

### CODE REVIEW

**Comment by aubergine10** [comment]
I've not had time to do extensive testing but as far as I can tell vehicles no longer lane change at the toll booth.

I did see a taxi do a u-turn at the end of a toll booth road however; it arrived via the 2-lane road, and then u-turned in the transition between that road and the 4-lane toll road, the node depicted in the image below:

utoll

Not sure if it was just already on its route and pathfinding got recalculated due to me slapping a toll booth in it's path, but seeing as the U-turn for that node is disabled it was bit odd. Also, should we disable u-turn features (including in UI) for all nodes that are part of a toll booth?

Also, not sure if I need to wait longer, but so far the toll booth isn't reporting any revenue from vehicles. Vehicles aren't stopping at the booth (the 'Automated Toll' policy is _not_ enabled). Maybe it's just too soon as all vehicles were already on the map when toll booth placed. I'll wait a bit longer.

**Comment by aubergine10** [comment]
Update: Vehicles are now stopping at the toll booth; I assume only vehicles spawned after the booth is placed will stop at it?

**Comment by VictorPhilipp** [comment]
All vehicles should stop at the tollbooth. It may require some seconds for the vehicles to "see" the new toll booth.

**Comment by aubergine10** [comment]
I had "Customisations come in to effect instantly" enabled on General tab in mod options. It took about 10 mins before (non-service) vehicles started stopping at the toll booth. To me it seemed that anything already spawned just drove straight through without stopping.

**Pull request merged**
