### PR TITLE
#245: Improved outside connection detection

### PR DESCRIPTION
**Pull request by VictorPhilipp**
fix checked, please re-check

### CODE REVIEW

**Comment by aubergine10** [comment]
Could the improved outside connection detection feed in to #100 (prevent immediate lane change when traffic spawns from outside connection) at later date? In #100 it checks based on spawn position, but seems it would be better to just check various flags?

**Comment by VictorPhilipp** [comment]
The problem is that neither flags nor frame positions give correct results. The only chance to check whether a citizen is located at an outside connection is at `StartPathFind` where we know the path starting position (`startPos`). When the method returns this information is lost.

**Comment by aubergine10** [comment]
Will test this evening.

**Comment by aubergine10** [comment]
I'm getting a mass of errors when I try to build this PR.

build error

**Comment by aubergine10** [comment]
Ah, forgot to set reference paths, doh!

**Pull request merged**
