### PR TITLE
Path-find stats & Benchmark profile fix

### PR DESCRIPTION
**Pull request by krzychu124**
Description:
- improved performance of path-find stats label
  - caches last value, apply only when changed (saves time which would be spent on rebuilding fonts cache and UI),
  - disables label component when path-find stats hidden(disabled),
  - disables label component when main menu hidden
- added missing directives to Benchmark profile,
- added button to reset benchmark data,

Additional changes:
- translation update:
  - Chinese Simplified - 田七不甜 (TianQiBuTian),
  - Chinese Traditional - 許景翔 (gk50125012),
  - Portuguese - Alan Willian Duarte (nipodemos13),
  - Japanese - mashitaro

### CODE REVIEW

**Comment by aubergine10** [comment]
Now we're using CrowdIn for translations, how should we attribute users who update or add languages?

**Comment by kvakvs** [comment]
Go to https://crowdin.com/project/tmpe/settings#members
And figure something out, like a group thanks to a list of names.

**Comment by krzychu124** [comment]
I will include a list of translators, but for now we usually have one person per language

**Comment by krzychu124** [comment]
I think it's ready for merge, any doubts, @aubergine10 ?

**Pull request merged**
