### PR TITLE
MSVS 2017 GitIgnore QuickFix

### PR DESCRIPTION
**Pull request by FireController1847**
Been seeing a lot more of these artifacts. Is Microsoft doing stuff or does this just happen to me on both my laptop and desktop? It's bad enough I have to ignore committing the csproj since my game's in a different location 😭

### CODE REVIEW

**Comment by krzychu124** [comment]
You don't have to change csproj files to change location of libs(folder Managed from game) 😉 

You just have to add game folder to "Reference paths" under Properties of every csproj 😄 It will create file BlahBlahBlah.csproj.user which doesn't have to be pushed to git 😃

**Comment by FireController1847** [comment]
@krzychu124 I have done that for the references, however I had to change the csproj due to the build events

gitkraken_2019-02-16_13-56-05

Thanks for pushing this :)

**Comment by krzychu124** [comment]
You don't have to change this file 😃 

Just in case you don't know what it does 😉 
Those lines are for quick workshop item update (look at that numbers at the end)
```255710``` - steamId of Cities Skylines 
```583429740``` - that's old steamId of LinuxFan TrafficManager which you can compare this number with old traffic manager link address

So you are updating downloaded old Traffic Manager workshop item changing those lines 😄 (I am sure you are not subscribed to this mod anyway)
If you build this mod it appears in Content Manager because postbuild script will copy those compiled sources to LOCALAPPDATA, not to steam workshop folder😉

**Comment by FireController1847** [comment]
Right, and that makes sense, but if I attempt to build it without modifying those in _some way_, such as deleting them or changing their directory, the build script fails to execute and you don't get that satisfaction of seeing "1 succeeded." It also provides a problem of not knowing when it _actually_ errors or not.

**Comment by krzychu124** [comment]
Ok, so I will remove those lines and everyone will be happy 😉

**Comment by FireController1847** [comment]
lol, okay

**Pull request merged**
