### PR TITLE
Update README for 10.21 Release

### PR DESCRIPTION
**Pull request by aubergine10**
Will push commits for changelog, etc., shortly.

### CODE REVIEW

**Comment by kvakvs** [comment]
For MPH speed limits you can clarify: 3 themes available to choose from: US, UK and German (default).

**Comment by aubergine10** [comment]
Yup, that's mentioned in the changelog - should it be added to the Features list too?

**Comment by kvakvs** [comment]
Ah, just looked down into features, it is all there, never mind

**Comment by aubergine10** [comment]
Anyone have any issues with me working the main README to look like this (it requires use of HTML tags, the images are stored external to the repo):

image

**Comment by FireController1847** [comment]
Maybe instead of embedding that image, we could make more note of the fact there is even documentation? Quite frankly I didn't know there was documentation until I needed it for DLS...

**Comment by aubergine10** [comment]
Yeah, I've already removed the toolbar image it's a bit grim. There's already a link to the docs so that should suffice for now.

**Comment by aubergine10** [comment]
Needs another review - just updates to the release notes since last review, see changes tab

**Comment by aubergine10** [comment]
One last change to add - don't merge yet

**Pull request merged**
