### PR TITLE
New remove_signs icon - updates #77

### PR DESCRIPTION
**Pull request by aubergine10**
* Replaced 'X' icon with trashcan icon (with an 'x' on it to aid familiarity with old icon).
* Made background a little darker to contrast better with new icon.

Will need testing in game (priority signs UI, and 'despawn' button on vehicle info panel) to make sure it works ok.

If any issues, take screenshot and attach to #77 and I will fix :)

### CODE REVIEW

**Comment by krzychu124** [comment]
Is new despawn button icon going to be added to this PR?

**Comment by aubergine10** [comment]
I thought same image was used for both?

**Comment by aubergine10** [comment]
ah,... does individual vehicle despawn use the remove-btn file instead? If so I can update that too (not sure what the button backgrounds in that file are for tho)

**Comment by krzychu124** [comment]
Yup, ```remove-btn.png``` atlas texture.

**Comment by aubergine10** [comment]
I'll send that in a separate PR if that's ok?

**Pull request merged**
